
package Shipment::Purolator::WSDL::Elements::Dimension;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://purolator.com/pws/datatypes/v1' }

__PACKAGE__->__set_name('Dimension');
__PACKAGE__->__set_nillable(1);
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    Shipment::Purolator::WSDL::Types::Dimension
);

}

1;


=pod

=head1 NAME

Shipment::Purolator::WSDL::Elements::Dimension

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
Dimension from the namespace http://purolator.com/pws/datatypes/v1.







=head1 METHODS

=head2 new

 my $element = Shipment::Purolator::WSDL::Elements::Dimension->new($data);

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDL::Types::Dimension
   Value =>  $some_value, # decimal
   DimensionUnit => $some_value, # DimensionUnit
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

