
package Shipment::Purolator::WSDL::Elements::GetShipmentManifestDocumentResponseContainer;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://purolator.com/pws/datatypes/v1' }

__PACKAGE__->__set_name('GetShipmentManifestDocumentResponseContainer');
__PACKAGE__->__set_nillable(1);
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    Shipment::Purolator::WSDL::Types::GetShipmentManifestDocumentResponseContainer
);

}

1;


=pod

=head1 NAME

Shipment::Purolator::WSDL::Elements::GetShipmentManifestDocumentResponseContainer

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetShipmentManifestDocumentResponseContainer from the namespace http://purolator.com/pws/datatypes/v1.







=head1 METHODS

=head2 new

 my $element = Shipment::Purolator::WSDL::Elements::GetShipmentManifestDocumentResponseContainer->new($data);

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDL::Types::GetShipmentManifestDocumentResponseContainer
   ManifestBatches =>  { # Shipment::Purolator::WSDL::Types::ArrayOfManifestBatch
     ManifestBatch =>  { # Shipment::Purolator::WSDL::Types::ManifestBatch
       ShipmentManifestDate =>  $some_value, # string
       ManifestCloseDateTime =>  $some_value, # string
       ManifestBatchDetails =>  { # Shipment::Purolator::WSDL::Types::ArrayOfManifestBatchDetail
         ManifestBatchDetail =>  { # Shipment::Purolator::WSDL::Types::ManifestBatchDetail
           DocumentType =>  $some_value, # string
           Description =>  $some_value, # string
           DocumentStatus => $some_value, # DocumentStatus
           URL =>  $some_value, # string
         },
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

