package Shipment::Purolator::WSDL::Types::OptionPrice;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Amount_of :ATTR(:get<Amount>);
my %ID_of :ATTR(:get<ID>);
my %Description_of :ATTR(:get<Description>);

__PACKAGE__->_factory(
    [ qw(        Amount
        ID
        Description

    ) ],
    {
        'Amount' => \%Amount_of,
        'ID' => \%ID_of,
        'Description' => \%Description_of,
    },
    {
        'Amount' => 'SOAP::WSDL::XSD::Typelib::Builtin::decimal',
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Description' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'Amount' => 'Amount',
        'ID' => 'ID',
        'Description' => 'Description',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDL::Types::OptionPrice

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
OptionPrice from the namespace http://purolator.com/pws/datatypes/v1.

OptionPrice




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Amount (min/maxOccurs: 1/1)


=item * ID (min/maxOccurs: 1/1)


=item * Description (min/maxOccurs: 1/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDL::Types::OptionPrice
   Amount =>  $some_value, # decimal
   ID =>  $some_value, # string
   Description =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

