package Shipment::Purolator::WSDL::Types::VoidShipmentResponseContainer;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(Shipment::Purolator::WSDL::Types::ResponseContainer);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ResponseInformation_of :ATTR(:get<ResponseInformation>);
my %ShipmentVoided_of :ATTR(:get<ShipmentVoided>);

__PACKAGE__->_factory(
    [ qw(        ResponseInformation
        ShipmentVoided

    ) ],
    {
        'ResponseInformation' => \%ResponseInformation_of,
        'ShipmentVoided' => \%ShipmentVoided_of,
    },
    {
        'ResponseInformation' => 'Shipment::Purolator::WSDL::Types::ResponseInformation',
        'ShipmentVoided' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
    },
    {

        'ResponseInformation' => 'ResponseInformation',
        'ShipmentVoided' => 'ShipmentVoided',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDL::Types::VoidShipmentResponseContainer

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
VoidShipmentResponseContainer from the namespace http://purolator.com/pws/datatypes/v1.

VoidShipmentResponse




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ShipmentVoided (min/maxOccurs: 0/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDL::Types::VoidShipmentResponseContainer
   ShipmentVoided =>  $some_value, # boolean
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

