
package Shipment::Purolator::WSDLV2::Elements::GetServicesOptionsResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://purolator.com/pws/datatypes/v2' }

__PACKAGE__->__set_name('GetServicesOptionsResponse');
__PACKAGE__->__set_nillable(1);
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    Shipment::Purolator::WSDLV2::Types::GetServicesOptionsResponseContainer
);

}

1;


=pod

=head1 NAME

Shipment::Purolator::WSDLV2::Elements::GetServicesOptionsResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetServicesOptionsResponse from the namespace http://purolator.com/pws/datatypes/v2.







=head1 METHODS

=head2 new

 my $element = Shipment::Purolator::WSDLV2::Elements::GetServicesOptionsResponse->new($data);

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDLV2::Types::GetServicesOptionsResponseContainer
   Services =>  { # Shipment::Purolator::WSDLV2::Types::ArrayOfService
     Service =>  { # Shipment::Purolator::WSDLV2::Types::Service
       ID =>  $some_value, # string
       Description =>  $some_value, # string
       PackageType =>  $some_value, # string
       PackageTypeDescription =>  $some_value, # string
       Options =>  { # Shipment::Purolator::WSDLV2::Types::ArrayOfOption
         Option =>  { # Shipment::Purolator::WSDLV2::Types::Option
           ID =>  $some_value, # string
           Description =>  $some_value, # string
           ValueType => $some_value, # ValueType
           AvailableForPieces =>  $some_value, # boolean
           PossibleValues =>  { # Shipment::Purolator::WSDLV2::Types::ArrayOfOptionValue
             OptionValue =>  { # Shipment::Purolator::WSDLV2::Types::OptionValue
               Value =>  $some_value, # string
               Description =>  $some_value, # string
             },
           },
         },
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

