package MyElements::GenerateBarCodeResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.webservicex.net/' }

__PACKAGE__->__set_name('GenerateBarCodeResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GenerateBarCodeResult_of :ATTR(:get<GenerateBarCodeResult>);

__PACKAGE__->_factory(
    [ qw(
        GenerateBarCodeResult
    ) ],
    {
        GenerateBarCodeResult => \%GenerateBarCodeResult_of,
    },
    {
        GenerateBarCodeResult => 'SOAP::WSDL::XSD::Typelib::Builtin::base64Binary',
    }
);

} # end BLOCK







} # end of BLOCK
1;

# __END__

=pod

=head1 NAME

MyElements::GenerateBarCodeResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GenerateBarCodeResponse from the namespace http://www.webservicex.net/.

=head1 METHODS

=head2 new

 my $element = MyElements::GenerateBarCodeResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   GenerateBarCodeResult =>  $some_value, # base64Binary
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

