
package MyElements::GetSpecificCookie;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx' }

__PACKAGE__->__set_name('GetSpecificCookie');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %index_of :ATTR(:get<index>);

__PACKAGE__->_factory(
    [ qw(        index

    ) ],
    {
        'index' => \%index_of,
    },
    {
        'index' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
    },
    {

        'index' => 'index',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::GetSpecificCookie

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetSpecificCookie from the namespace http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * index

 $element->set_index($data);
 $element->get_index();




=back


=head1 METHODS

=head2 new

 my $element = MyElements::GetSpecificCookie->new($data);

Constructor. The following data structure may be passed to new():

 {
   index =>  $some_value, # int
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

