package Shipment::FedEx::WSDL::TrackTypes::SpecialInstructionStatusDetail;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://fedex.com/ws/track/v9' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Status_of :ATTR(:get<Status>);
my %StatusCreateTime_of :ATTR(:get<StatusCreateTime>);

__PACKAGE__->_factory(
    [ qw(        Status
        StatusCreateTime

    ) ],
    {
        'Status' => \%Status_of,
        'StatusCreateTime' => \%StatusCreateTime_of,
    },
    {
        'Status' => 'Shipment::FedEx::WSDL::TrackTypes::SpecialInstructionsStatusCode',
        'StatusCreateTime' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
    },
    {

        'Status' => 'Status',
        'StatusCreateTime' => 'StatusCreateTime',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::FedEx::WSDL::TrackTypes::SpecialInstructionStatusDetail

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SpecialInstructionStatusDetail from the namespace http://fedex.com/ws/track/v9.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Status


=item * StatusCreateTime




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::FedEx::WSDL::TrackTypes::SpecialInstructionStatusDetail
   Status => $some_value, # SpecialInstructionsStatusCode
   StatusCreateTime =>  $some_value, # dateTime
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

