=pod

=head1 NAME

SOAP::WSDL::Manual::Serializer

=head1 SERIALIZER CLASSES

Serializer classes convert perl data structures to XML.

SOAP::WSDL comes with one builtin serializer class:
L<SOAP::WSDL::Serializer::XSD|SOAP::WSDL::Serializer::XSD>.

=head1 WRITING YOUR OWN SERIALIZER

See L<SOAP::WSDL::Factory::Serializer>.

=head1 LICENSE

Copyright 2007 Martin Kutter.

This file is part of SOAP-WSDL. You may distribute/modify it under
the same terms as perl itself

=head1 AUTHOR

Martin Kutter E<lt>martin.kutter fen-net.deE<gt>

=cut
 