package Shipment::UPS::WSDL::RateTypes::OnCallPickupType;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Schedule_of :ATTR(:get<Schedule>);

__PACKAGE__->_factory(
    [ qw(        Schedule

    ) ],
    {
        'Schedule' => \%Schedule_of,
    },
    {
        'Schedule' => 'Shipment::UPS::WSDL::RateTypes::ScheduleType',
    },
    {

        'Schedule' => 'Schedule',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::UPS::WSDL::RateTypes::OnCallPickupType

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
OnCallPickupType from the namespace http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Schedule (min/maxOccurs: 1/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::UPS::WSDL::RateTypes::OnCallPickupType
   Schedule =>  { # Shipment::UPS::WSDL::RateTypes::ScheduleType
     PickupDay =>  $some_value, # string
     Method =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

