package Shipment::Purolator::WSDLV2::Types::ArrayOfOptionValue;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v2' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %OptionValue_of :ATTR(:get<OptionValue>);

__PACKAGE__->_factory(
    [ qw(        OptionValue

    ) ],
    {
        'OptionValue' => \%OptionValue_of,
    },
    {
        'OptionValue' => 'Shipment::Purolator::WSDLV2::Types::OptionValue',
    },
    {

        'OptionValue' => 'OptionValue',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDLV2::Types::ArrayOfOptionValue

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfOptionValue from the namespace http://purolator.com/pws/datatypes/v2.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * OptionValue (min/maxOccurs: 0/unbounded)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDLV2::Types::ArrayOfOptionValue
   OptionValue =>  { # Shipment::Purolator::WSDLV2::Types::OptionValue
     Value =>  $some_value, # string
     Description =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

