package Shipment::Purolator::WSDLV2::Types::CreateReturnsManagementShipmentResponseContainer;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v2' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(Shipment::Purolator::WSDLV2::Types::ResponseContainer);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ResponseInformation_of :ATTR(:get<ResponseInformation>);
my %ShipmentPIN_of :ATTR(:get<ShipmentPIN>);
my %PiecePINs_of :ATTR(:get<PiecePINs>);
my %RMA_of :ATTR(:get<RMA>);

__PACKAGE__->_factory(
    [ qw(        ResponseInformation
        ShipmentPIN
        PiecePINs
        RMA

    ) ],
    {
        'ResponseInformation' => \%ResponseInformation_of,
        'ShipmentPIN' => \%ShipmentPIN_of,
        'PiecePINs' => \%PiecePINs_of,
        'RMA' => \%RMA_of,
    },
    {
        'ResponseInformation' => 'Shipment::Purolator::WSDLV2::Types::ResponseInformation',
        'ShipmentPIN' => 'Shipment::Purolator::WSDLV2::Types::PIN',
        'PiecePINs' => 'Shipment::Purolator::WSDLV2::Types::ArrayOfPIN',
        'RMA'       => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ResponseInformation' => 'ResponseInformation',
        'ShipmentPIN' => 'ShipmentPIN',
        'PiecePINs' => 'PiecePINs',
        'RMA'       => 'RMA',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDLV2::Types::CreateReturnsManagementShipmentResponseContainer

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CreateReturnsManagementShipmentResponseContainer from the namespace http://purolator.com/pws/datatypes/v2.

CreateReturnsManagementShipmentResponse

=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ShipmentPIN (min/maxOccurs: 0/1)

=item * PiecePINs (min/maxOccurs: 0/1)

=item * RMA (min/maxOccurs: 0/1)

=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDLV2::Types::CreateShipmentResponseContainer
   ShipmentPIN =>  { # Shipment::Purolator::WSDLV2::Types::PIN
     Value =>  $some_value, # string
   },
   PiecePINs =>  { # Shipment::Purolator::WSDLV2::Types::ArrayOfPIN
     PIN => {}, # Shipment::Purolator::WSDLV2::Types::PIN
   },
   RMA => # SOAP::WSDL::XSD::Typelib::Builtin::string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

