package Shipment::Purolator::WSDLV2::Types::TotalWeight;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v2' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Value_of :ATTR(:get<Value>);
my %WeightUnit_of :ATTR(:get<WeightUnit>);

__PACKAGE__->_factory(
    [ qw(        Value
        WeightUnit

    ) ],
    {
        'Value' => \%Value_of,
        'WeightUnit' => \%WeightUnit_of,
    },
    {
        'Value' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'WeightUnit' => 'Shipment::Purolator::WSDLV2::Types::WeightUnit',
    },
    {

        'Value' => 'Value',
        'WeightUnit' => 'WeightUnit',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDLV2::Types::TotalWeight

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
TotalWeight from the namespace http://purolator.com/pws/datatypes/v2.

TotalWeight




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Value (min/maxOccurs: 1/1)


=item * WeightUnit (min/maxOccurs: 1/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDLV2::Types::TotalWeight
   Value =>  $some_value, # int
   WeightUnit => $some_value, # WeightUnit
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

