package Shipment::UPS::WSDL::ShipTypes::LicenseType;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.ups.com/XMLSchema/XOLTWS/IF/v1.0' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Number_of :ATTR(:get<Number>);
my %Date_of :ATTR(:get<Date>);
my %ExceptionCode_of :ATTR(:get<ExceptionCode>);

__PACKAGE__->_factory(
    [ qw(        Number
        Date
        ExceptionCode

    ) ],
    {
        'Number' => \%Number_of,
        'Date' => \%Date_of,
        'ExceptionCode' => \%ExceptionCode_of,
    },
    {
        'Number' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Date' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ExceptionCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'Number' => 'Number',
        'Date' => 'Date',
        'ExceptionCode' => 'ExceptionCode',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::UPS::WSDL::ShipTypes::LicenseType

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
LicenseType from the namespace http://www.ups.com/XMLSchema/XOLTWS/IF/v1.0.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Number (min/maxOccurs: 0/1)


=item * Date (min/maxOccurs: 0/1)


=item * ExceptionCode (min/maxOccurs: 0/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::UPS::WSDL::ShipTypes::LicenseType
   Number =>  $some_value, # string
   Date =>  $some_value, # string
   ExceptionCode =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

