package Shipment::Purolator::WSDL::Types::ArrayOfContentDetail;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ContentDetail_of :ATTR(:get<ContentDetail>);

__PACKAGE__->_factory(
    [ qw(        ContentDetail

    ) ],
    {
        'ContentDetail' => \%ContentDetail_of,
    },
    {
        'ContentDetail' => 'Shipment::Purolator::WSDL::Types::ContentDetail',
    },
    {

        'ContentDetail' => 'ContentDetail',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDL::Types::ArrayOfContentDetail

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfContentDetail from the namespace http://purolator.com/pws/datatypes/v1.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ContentDetail (min/maxOccurs: 0/unbounded)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDL::Types::ArrayOfContentDetail
   ContentDetail =>  { # Shipment::Purolator::WSDL::Types::ContentDetail
     Description =>  $some_value, # string
     HarmonizedCode =>  $some_value, # string
     CountryOfManufacture =>  $some_value, # string
     ProductCode =>  $some_value, # string
     UnitValue =>  $some_value, # decimal
     Quantity =>  $some_value, # int
     NAFTADocumentIndicator =>  $some_value, # boolean
     FDADocumentIndicator =>  $some_value, # boolean
     FCCDocumentIndicator =>  $some_value, # boolean
     SenderIsProducerIndicator =>  $some_value, # boolean
     TextileIndicator =>  $some_value, # boolean
     TextileManufacturer =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

