package Shipment::Purolator::WSDL::Types::ArrayOfOptionRule;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %OptionRule_of :ATTR(:get<OptionRule>);

__PACKAGE__->_factory(
    [ qw(        OptionRule

    ) ],
    {
        'OptionRule' => \%OptionRule_of,
    },
    {
        'OptionRule' => 'Shipment::Purolator::WSDL::Types::OptionRule',
    },
    {

        'OptionRule' => 'OptionRule',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDL::Types::ArrayOfOptionRule

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfOptionRule from the namespace http://purolator.com/pws/datatypes/v1.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * OptionRule (min/maxOccurs: 0/unbounded)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDL::Types::ArrayOfOptionRule
   OptionRule =>  { # Shipment::Purolator::WSDL::Types::OptionRule
     OptionIDValuePair =>  { # Shipment::Purolator::WSDL::Types::OptionIDValuePair
       ID =>  $some_value, # string
       Value =>  $some_value, # string
     },
     Exclusions =>  { # Shipment::Purolator::WSDL::Types::ArrayOfOptionIDValuePair
       OptionIDValuePair => {}, # Shipment::Purolator::WSDL::Types::OptionIDValuePair
     },
     Inclusions => {}, # Shipment::Purolator::WSDL::Types::ArrayOfOptionIDValuePair
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

