package Shipment::Purolator::WSDL::Types::PickupInformation;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://purolator.com/pws/datatypes/v1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %PickupType_of :ATTR(:get<PickupType>);

__PACKAGE__->_factory(
    [ qw(        PickupType

    ) ],
    {
        'PickupType' => \%PickupType_of,
    },
    {
        'PickupType' => 'Shipment::Purolator::WSDL::Types::PickupType',
    },
    {

        'PickupType' => 'PickupType',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::Purolator::WSDL::Types::PickupInformation

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
PickupInformation from the namespace http://purolator.com/pws/datatypes/v1.

PickupInformation




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * PickupType (min/maxOccurs: 1/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::Purolator::WSDL::Types::PickupInformation
   PickupType => $some_value, # PickupType
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

