package Shipment::FedEx::WSDL::CloseTypes::SmartPostCloseRequest;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://fedex.com/ws/close/v2' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %WebAuthenticationDetail_of :ATTR(:get<WebAuthenticationDetail>);
my %ClientDetail_of :ATTR(:get<ClientDetail>);
my %TransactionDetail_of :ATTR(:get<TransactionDetail>);
my %Version_of :ATTR(:get<Version>);
my %HubId_of :ATTR(:get<HubId>);
my %CustomerManifestId_of :ATTR(:get<CustomerManifestId>);
my %DestinationCountryCode_of :ATTR(:get<DestinationCountryCode>);
my %PickUpCarrier_of :ATTR(:get<PickUpCarrier>);

__PACKAGE__->_factory(
    [ qw(        WebAuthenticationDetail
        ClientDetail
        TransactionDetail
        Version
        HubId
        CustomerManifestId
        DestinationCountryCode
        PickUpCarrier

    ) ],
    {
        'WebAuthenticationDetail' => \%WebAuthenticationDetail_of,
        'ClientDetail' => \%ClientDetail_of,
        'TransactionDetail' => \%TransactionDetail_of,
        'Version' => \%Version_of,
        'HubId' => \%HubId_of,
        'CustomerManifestId' => \%CustomerManifestId_of,
        'DestinationCountryCode' => \%DestinationCountryCode_of,
        'PickUpCarrier' => \%PickUpCarrier_of,
    },
    {
        'WebAuthenticationDetail' => 'Shipment::FedEx::WSDL::CloseTypes::WebAuthenticationDetail',
        'ClientDetail' => 'Shipment::FedEx::WSDL::CloseTypes::ClientDetail',
        'TransactionDetail' => 'Shipment::FedEx::WSDL::CloseTypes::TransactionDetail',
        'Version' => 'Shipment::FedEx::WSDL::CloseTypes::VersionId',
        'HubId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'CustomerManifestId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DestinationCountryCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'PickUpCarrier' => 'Shipment::FedEx::WSDL::CloseTypes::CarrierCodeType',
    },
    {

        'WebAuthenticationDetail' => 'WebAuthenticationDetail',
        'ClientDetail' => 'ClientDetail',
        'TransactionDetail' => 'TransactionDetail',
        'Version' => 'Version',
        'HubId' => 'HubId',
        'CustomerManifestId' => 'CustomerManifestId',
        'DestinationCountryCode' => 'DestinationCountryCode',
        'PickUpCarrier' => 'PickUpCarrier',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::FedEx::WSDL::CloseTypes::SmartPostCloseRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SmartPostCloseRequest from the namespace http://fedex.com/ws/close/v2.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * WebAuthenticationDetail (min/maxOccurs: 1/1)


=item * ClientDetail (min/maxOccurs: 1/1)


=item * TransactionDetail (min/maxOccurs: 0/1)


=item * Version (min/maxOccurs: 1/1)


=item * HubId (min/maxOccurs: 0/1)


=item * CustomerManifestId (min/maxOccurs: 0/1)


=item * DestinationCountryCode (min/maxOccurs: 0/1)


=item * PickUpCarrier (min/maxOccurs: 0/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::FedEx::WSDL::CloseTypes::SmartPostCloseRequest
   WebAuthenticationDetail =>  { # Shipment::FedEx::WSDL::CloseTypes::WebAuthenticationDetail
     UserCredential =>  { # Shipment::FedEx::WSDL::CloseTypes::WebAuthenticationCredential
       Key =>  $some_value, # string
       Password =>  $some_value, # string
     },
   },
   ClientDetail =>  { # Shipment::FedEx::WSDL::CloseTypes::ClientDetail
     AccountNumber =>  $some_value, # string
     MeterNumber =>  $some_value, # string
     IntegratorId =>  $some_value, # string
     Localization =>  { # Shipment::FedEx::WSDL::CloseTypes::Localization
       LanguageCode =>  $some_value, # string
       LocaleCode =>  $some_value, # string
     },
   },
   TransactionDetail =>  { # Shipment::FedEx::WSDL::CloseTypes::TransactionDetail
     CustomerTransactionId =>  $some_value, # string
     Localization => {}, # Shipment::FedEx::WSDL::CloseTypes::Localization
   },
   Version =>  { # Shipment::FedEx::WSDL::CloseTypes::VersionId
     ServiceId =>  $some_value, # string
     Major =>  $some_value, # int
     Intermediate =>  $some_value, # int
     Minor =>  $some_value, # int
   },
   HubId =>  $some_value, # string
   CustomerManifestId =>  $some_value, # string
   DestinationCountryCode =>  $some_value, # string
   PickUpCarrier => $some_value, # CarrierCodeType
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

