package MyElements::GetCitiesByCountry;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.webserviceX.NET' }

__PACKAGE__->__set_name('GetCitiesByCountry');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %CountryName_of :ATTR(:get<CountryName>);

__PACKAGE__->_factory(
    [ qw(
        CountryName
    ) ],
    {
        CountryName => \%CountryName_of,
    },
    {
        CountryName => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    }
);

} # end BLOCK







} # end of BLOCK
1;

# __END__

=pod

=head1 NAME

MyElements::GetCitiesByCountry

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetCitiesByCountry from the namespace http://www.webserviceX.NET.

=head1 METHODS

=head2 new

 my $element = MyElements::GetCitiesByCountry->new($data);

Constructor. The following data structure may be passed to new():

 {
   CountryName =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

