package Shipment::UPS::WSDL::TrackTypes::DeliveryDetailType;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Type_of :ATTR(:get<Type>);
my %Date_of :ATTR(:get<Date>);
my %Time_of :ATTR(:get<Time>);

__PACKAGE__->_factory(
    [ qw(        Type
        Date
        Time

    ) ],
    {
        'Type' => \%Type_of,
        'Date' => \%Date_of,
        'Time' => \%Time_of,
    },
    {
        'Type' => 'Shipment::UPS::WSDL::TrackTypes::CommonCodeDescriptionType',
        'Date' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Time' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'Type' => 'Type',
        'Date' => 'Date',
        'Time' => 'Time',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::UPS::WSDL::TrackTypes::DeliveryDetailType

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
DeliveryDetailType from the namespace http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Type


=item * Date


=item * Time




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::UPS::WSDL::TrackTypes::DeliveryDetailType
   Type =>  { # Shipment::UPS::WSDL::TrackTypes::CommonCodeDescriptionType
     Code =>  $some_value, # string
     Description =>  $some_value, # string
   },
   Date =>  $some_value, # string
   Time =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

